Add netbsd-curses support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -278,6 +278,23 @@ EOF
   fi
 }
 
+netbsdcursescheck() {
+  cat << EOF > conftest.c
+#include <term.h>
+#include <curses.h>
+int main(void){setupterm(NULL, 0, NULL);return 0;}
+EOF
+  $cc $cflags -o conftest.o -c conftest.c > /dev/null 2>&1
+  $cc $ldflags -o conftest conftest.o -lcurses -lterminfo > /dev/null 2>&1
+  if [ $? -eq 0 ] ; then
+    rm -f conftest conftest.o conftest.c
+    return 0
+  else
+    rm -f conftest conftest.o conftest.c
+    return 1
+  fi
+}
+
 deadcheck() {
   cat << EOF > conftest.c
 #include <stdlib.h>
@@ -1187,21 +1204,28 @@ if [ $curses -eq 1 ] ; then
     echo "#define HAVE_CURSES" >> pconfig.h
     echo "curses.h"
   else
-    ncursescheck
+    netbsdcursescheck
     if [ $? -eq 0 ] ; then
-      libs="$libs -lncurses"
-      echo "#define HAVE_NCURSES" >> pconfig.h
-      echo "ncurses.h"
+      libs="$libs -lcurses -lterminfo"
+      echo "#define HAVE_CURSES" >> pconfig.h
+      echo "curses.h (netbsd-curses)"
     else
-      ncursesncursescheck
+      ncursescheck
       if [ $? -eq 0 ] ; then
-	libs="$libs -lncurses"
-	echo "#define HAVE_NCURSESNCURSES" >> pconfig.h
-	echo "ncurses/ncurses.h"
+        libs="$libs -lncurses"
+        echo "#define HAVE_NCURSES" >> pconfig.h
+        echo "ncurses.h"
       else
-	echo "#define NO_CURSES" >> pconfig.h
-	echo "not found"
-	echo "oksh will be built without screen clearing support"
+        ncursesncursescheck
+        if [ $? -eq 0 ] ; then
+          libs="$libs -lncurses"
+          echo "#define HAVE_NCURSESNCURSES" >> pconfig.h
+          echo "ncurses/ncurses.h"
+        else
+          echo "#define NO_CURSES" >> pconfig.h
+          echo "not found"
+          echo "oksh will be built without screen clearing support"
+        fi
       fi
     fi
   fi
